USE [master]
GO

/****** Object:  Database [BANK_INFO]    Script Date: 30-01-2023 13:25:32 ******/
CREATE DATABASE [BANK_INFO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BANK_INFO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\BANK_INFO.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BANK_INFO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\BANK_INFO_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BANK_INFO] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BANK_INFO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BANK_INFO] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BANK_INFO] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BANK_INFO] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BANK_INFO] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BANK_INFO] SET ARITHABORT OFF 
GO

ALTER DATABASE [BANK_INFO] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [BANK_INFO] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BANK_INFO] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BANK_INFO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BANK_INFO] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BANK_INFO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BANK_INFO] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BANK_INFO] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BANK_INFO] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BANK_INFO] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BANK_INFO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BANK_INFO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BANK_INFO] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BANK_INFO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BANK_INFO] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BANK_INFO] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BANK_INFO] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BANK_INFO] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BANK_INFO] SET  MULTI_USER 
GO

ALTER DATABASE [BANK_INFO] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BANK_INFO] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BANK_INFO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BANK_INFO] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BANK_INFO] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BANK_INFO] SET  READ_WRITE 
GO

